from typing import Self

from abc import ABC, ABCMeta, abstractmethod

from auto_compiler.source import Source


class MetaCompiler(ABCMeta):
    __inheritors__ = set()

    def __new__(cls, name, bases, dict):
        subclass = super().__new__(cls, name, bases, dict)
        cls.__inheritors__.update(subclass.mro()[:-3])
        return subclass


class Compiler(ABC, metaclass=MetaCompiler):
    supported_files: list[str]

    @abstractmethod
    def __init__(self):
        ...

    @abstractmethod
    def build_files(self, files: list[Source]) -> list[str]:
        """
            Builds all files in files and returns the paths to the executables
        """
        ...

    @abstractmethod
    def build_file(self, file: Source) -> str:
        """
           Builds the file and returns the path to the executable 
        """
        ...

    @abstractmethod
    def clean_files(self) -> None:
        """
            Removes executable and eventual extra files generated by the build_files method
        """
        ...